[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x7596bc52cfc33ab955ebd97b4015c78537e9b1693b7e604d32f172bc1935d6f"
transaction_hash = "0x74f4ccc6389687a2137cf3df73366ecd4569d62ef1df111e77edf58d06ff989"
block_number = 3
seed = "moving_mountains_with_yu"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x161cd312632bea0e615cff6f7fddb44f26f0d0a13b573516f587a1f8a218bdb"
class_hash = "0x13a32b33353b48c62703828ccd8d287896d2d2ba052e750f5ada258d4ca2858"
original_class_hash = "0x13a32b33353b48c62703828ccd8d287896d2d2ba052e750f5ada258d4ca2858"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/moving_mountains_with_yu_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "moving_mountains_with_yu::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x54985dc281bebc7f80a08cf469344863ec975314c73e4134181e3d46b17d236"
original_class_hash = "0x54985dc281bebc7f80a08cf469344863ec975314c73e4134181e3d46b17d236"
abi = "abis/deployments/models/moving_mountains_with_yu_models_architecture_architecture.json"
name = "moving_mountains_with_yu::models::architecture::architecture"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "add_people"
type = "u256"
key = false

[[models.members]]
name = "lv"
type = "u256"
key = false

[[models.members]]
name = "mold"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x61905ddb39681cf0be32895fbb9bc91ce0d76fec061d2068c7b5a19103862b7"
original_class_hash = "0x61905ddb39681cf0be32895fbb9bc91ce0d76fec061d2068c7b5a19103862b7"
abi = "abis/deployments/models/moving_mountains_with_yu_models_base_click_base_click.json"
name = "moving_mountains_with_yu::models::base_click::base_click"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "add_people"
type = "u256"
key = false

[[models.members]]
name = "lv"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1cd1ee92cbdf482aff5742bbe501dd8a3fa788badc652b26bdab6d86efbdb0b"
original_class_hash = "0x1cd1ee92cbdf482aff5742bbe501dd8a3fa788badc652b26bdab6d86efbdb0b"
abi = "abis/deployments/models/moving_mountains_with_yu_models_people_people.json"
name = "moving_mountains_with_yu::models::people::people"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "people_count"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x79b84a9462c13925206294c7e4b061534f83281e953e2c95c10133851734b2f"
original_class_hash = "0x79b84a9462c13925206294c7e4b061534f83281e953e2c95c10133851734b2f"
abi = "abis/deployments/models/moving_mountains_with_yu_models_weapon_weapon.json"
name = "moving_mountains_with_yu::models::weapon::weapon"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "subtract_people"
type = "u256"
key = false

[[models.members]]
name = "lv"
type = "u256"
key = false

[[models.members]]
name = "weapon_type"
type = "u8"
key = false
